import logging
from enum import Enum


logger = logging.getLogger(__name__)


class Event(Enum):
    LOGIN_STARTED = "LOGIN STARTED"
    LOGIN_FAILED = "LOGIN_FAILED"
    LOGIN_INTERRUPTED = "LOGIN INTERRUPTED"
    LOGIN_FINISHED = "LOGIN FINISHED"

    TWO_FA_STARTED = "2FA STARTED"
    TWO_FA_FAILED = "2FA FAILED"
    TWO_FA_INTERRUPTED = "2FA INTERRUPTED"
    TWO_FA_FINISHED = "2FA FINISHED"

    ASKING_LLM_CHECK_LOGIN_STARTED = "ASKING LLM CHECK LOGIN STARTED"
    ASKING_LLM_CHECK_LOGIN_FINISHED = "ASKING LLM CHECK LOGIN FINISHED"

    ASKING_LLM_HANDLE_LOGIN_STARTED = "ASKING LLM HANDLE LOGIN STARTED"
    ASKING_LLM_HANDLE_LOGIN_FINISHED = "ASKING LLM HANDLE LOGIN FINISHED"

    ASKING_LLM_CHECK_2FA_STARTED = "ASKING LLM CHECK 2FA STARTED"
    ASKING_LLM_CHECK_2FA_FINISHED = "ASKING LLM CHECK 2FA FINISHED"

    ASKING_LLM_HANDLE_2FA_STARTED = "ASKING LLM HANDLE 2FA STARTED"
    ASKING_LLM_HANDLE_2FA_FINISHED = "ASKING LLM HANDLE 2FA FINISHED"

    ASKING_LLM_OBSERVE_PAGE_STARTED = "ASKING LLM OBSERVE PAGE STARTED"
    ASKING_LLM_OBSERVE_PAGE_FINISHED = "ASKING LLM OBSERVE PAGE FINISHED"


def log_event(event: Event):
    logger.info(event.value)
